sudo: required

services:
  - docker

before_install:
  - docker pull angoca/db2-instance
  - docker run -i -t --privileged=true --name="db2inst1" -p 50000:50000 angoca/db2-instance "./createInstance;exit"

script:
 - docker run db2inst1 db2 "create db test"
