sudo: required

services:
  - docker

before_install:
  - docker pull angoca/db2-instance
  - docker images
  - echo ./createInstance | docker run -i --privileged=true --name="db2inst1" -p 50001:50000 angoca/db2-instance
  - docker ps -a
  - docker start $(docker ps -a -q)

script:
 - docker exec $(docker ps -a -q) su -c ". ~db2inst1/sqllib/db2profile ; db2 create db test" db2inst1
